name: Test

on: push

jobs:
  verify_templates_compiled:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-ruby@v1
    - uses: actions/checkout@v2
    - run: gem install bundler
    - run: bundle install --without=development
    - run: make compile
    - run: git diff --exit-code

  redis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-ruby@v1
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2-beta
    - run: go get golang.org/x/tools/cmd/goimports
    - run: env
    - run: gem install bundler
    - run: bundle install --without=development
    - run: make test_redis

  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-ruby@v1
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2-beta
    - run: go get golang.org/x/tools/cmd/goimports
    - run: env
    - run: gem install bundler
    - run: bundle install --without=development
    - run: make test_docker
